{{- if not .Values.operatorNamespaced }}
# Create this file only when the operator is meant to run clusterwide
{{- if .Values.rbacEnable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ template "habitat-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "habitat-operator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "habitat-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "habitat-operator.fullname" . }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- else}}
  namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}
{{- end }}
