{{- if .Values.operatorNamespaced }}
# Create this file only when the operator is meant to run in a namespace
# Since in a clusterwide setup operator itself would register a CRD
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: habitats.habitat.sh
spec:
  group: habitat.sh
  names:
    kind: Habitat
    listKind: HabitatList
    plural: habitats
    shortNames:
    - hab
    singular: habitat
  scope: Namespaced
  version: v1beta1
{{- end }}
